### ISSUE TITLE
Failure to replace the following non-ASCII characters

### ISSUE THREAD

**Issue by carolinefmoyer** [njlyon0/supportR#10]
âE^TM should be translated to '

\u00e2E^TM should also be translated to '

**Comment by njlyon0** [comment]
Hi @carolinefmoyer !

Thanks for opening this issue! Just to make sure I'm understanding you correctly, you want `âE^TM` to be replaced with `'` by the `replace_non_ascii` function? When I run the function on the characters you provided I get the following:

```
# Including letters
supportR::replace_non_ascii(x = "âE^TM", include_letters = TRUE)
##> [1] "aE^TM"
```

Is that not the behavior you want/would expect from this function?

**Comment by carolinefmoyer** [comment]
Hi Nick, thanks for getting back to me!

I believe â€™, as well as â\200\231, both get translated from ’ (RIGHT SINGLE QUOTATION MARK - U+2019). Here’s a screenshot of what things look like in RStudio. Notice that in the source tab, both â\200\231 and  â€™ get printed as â€™, while in the environment tab, they both get displayed as â\200\231.

***@***.***

Related post about â\200\231: https://stackoverflow.com/questions/59838304/how-can-i-change-an-apostrophe-into-a-single-unit-instead-of-3-bytes-342-200
Related post about â€™: https://stackoverflow.com/questions/2477452/%C3%A2%E2%82%AC-showing-on-page-instead-of

I’m not super savvy with character encoding, but I hope the above explanation helps.

Caroline Moyer, MSW, PMP
she/her/hers | Why do I put my pronouns in my signature?<https://www.mypronouns.org/>
Pronounced “Carolyn”
Research Data Specialist II
Research, Automation, and Data Division (RADD)
(916) 207-2205 | ***@***.******@***.***>

**Comment by njlyon0** [comment]
Hey Caroline,

Hmm, that helps but it looks like your screenshot didn't get translated correctly from email to GitHub issue. Would you mind attaching it to the issue directly? You may need to click "View it on GitHub" on the bottom of the email you'll likely receive from this comment.

Also, I'm still not totally clear on the specific error / incorrect behavior you're seeing. Would you mind copy/pasting the relevant lines of the code you're running and what it returns into this issue?

That might look like what I've inserted below:

```
replace_non_ascii(x = "â€™", include_letters = TRUE)
## [1] "aE^TM"
```

**Comment by carolinefmoyer** [comment]
Hi Nick, sorry about that. I've included the screenshot, as well as the code and results below.
```
phrase1 <- "six monthsâ\200\231 full-time schooling"
phrase2 <- "the manufacturerâ€™s operating instructions"

print(phrase1)
[1] "six monthsâ€™ full-time schooling"

print(phrase2)
[1] "the manufacturerâ€™s operating instructions"

phrase1_mod <- supportR::replace_non_ascii(x = phrase1, include_letters = TRUE)
phrase2_mod <- supportR::replace_non_ascii(x = phrase2, include_letters = TRUE)

print(phrase1_mod) # Desired output: six months' full-time schooling
[1] "six monthsaE^TM full-time schooling"

print(phrase2_mod) # Desired output: the manufacturer's operating instructions
[1] "the manufactureraE^TMs operating instructions"
```

![image](https://github.com/user-attachments/assets/56ade2be-1f4e-4a15-9dcc-ffe5006c257e)

**Comment by njlyon0** [comment]
Ah that is helpful clarification, thanks!

This is an interesting edge case because it looks to me like `phrase1` and `phrase2` actually have `â€™` instead of `’` (right-facing apostrophe). That says to me that it's actually the initial reading into R that mangles the apostrophe rather than `replace_non_ascii()` doing some sort of bad replacement.

If you run `replace_non_ascii` on a right facing apostrophe directly you do get the correct conversion (to a generic apostrophe--see below).

```
supportR::replace_non_ascii(x = "’")
## [1] "'"
```

My concern in editing `replace_non_ascii` to replace `â€™` with `'` is that there might be a case where someone wants `â€™` to be replaced with ASCII equivalents on a character-by-character basis and this "fix" to the function would be an unpredictable behavior for that user.

How did you read the original text into R? If non-ASCII right-facing apostrophes are consistently read into R and malformed like this (i.e., into this set of non-apostrophe, non-ASCII characters) I'd feel better about tweaking the behavior of the function without fear of accidentally creating a different error for someone else.

**Comment by carolinefmoyer** [comment]
That makes sense, and I totally understand if this is outside the scope of the package. I’ve actually built a custom function to take care of these cases in my current project, so I’ve found a workable solution for now.

I just did a little more investigating, and it looks like if I read in those weird characters (fancy apostrophe or non-breaking space) into RStudio from an .xlsx file, they read in well, printing as those non-ascii characters. From there I could use your package to clean them. It looks like the problem comes when I don’t clean them at that point, then export them to .csv. When I open the .csv, the characters are messed up. So it looks like I need to implement your package earlier in my process, and that should help.

So if you’re worried about edge cases, don’t worry about adjusting anything, I think I’ve got a workable solution going forward 😊

Let me know if you agree with that thinking. Thank you for the back-and-forth! I appreciate your time!

Caroline Moyer, MSW, PMP
she/her/hers | Why do I put my pronouns in my signature?<https://www.mypronouns.org/>
Pronounced “Carolyn”
Research Data Specialist II
Research, Automation, and Data Division (RADD)
(916) 207-2205 | ***@***.******@***.***>

**Comment by njlyon0** [comment]
Thanks for explaining that, that's good to know how the reading in then exporting combines to change those characters in such a strange way.

Glad that my function is useful to you and that just changing when you use it in your workflow will likely solve the issue!

I'm always excited to chat with folx who are finding value in `supportR` so it was great talking with you about this.

I'll go ahead and close this issue now then but please don't hesitate to open a new one if you ever encounter other issues with this package!
